### ISSUE TITLE
ability to make squares/circles

### ISSUE THREAD

**Issue by e-volusian** [antfu/live-draw#1]
Hey, I really like live-draw. It's very slick and stylish. I am usually anti-animation but I like them in this case :-)  Very well done

I'm looking for a replacement for [ZoomIt](https://docs.microsoft.com/en-us/sysinternals/downloads/zoomit) which is very old a this point. 

The one feature I miss from ZoomIt is that you can hold down CTRL and make nice squares or SHIFT to make nice circles (see below for example). Any chance of such a feature in live-draw?

![image](https://user-images.githubusercontent.com/7467373/37103515-0c56a48e-21f0-11e8-99de-3fa4494ef83f.png)

**Comment by antfu** [comment]
Nice advice, thanks. Will definitely take it into consideration.

But my apologize that I do not have much time maintaining this project currently. So you may not see it coming very soon. I am sorry.

Anyway, thank you again for such a good advice. And also, any pull requests is welcome.

**Comment by ab28dev** [comment]
This feature will be implemented within this year as this is a necessary feature.
