### ISSUE TITLE
how to create shortcuts?

### ISSUE THREAD

**Issue by iannortnau** [antfu/live-draw#10]
is there any way to create shortcuts? how to press ctrl + 1 to use the pen and ctrl + 2 to activate the eraser?

if there is no, would there be any way to implement it?

I really loved the program it is very good literally the best I have used so far being that I paid $$ 79 for a program with the same purpose and yours is much better, I just really would like to have shortcuts

thank you for your attention

iann ortnau

**Comment by marc-antoine-girard** [comment]
@iannortnau I cloned the repo a while ago and added some shortcuts. I could do a PR this week, I just don't know if @antfu takes pull requests. In any cases, I'll leave a comment here when it's done.

**Comment by iannortnau** [comment]
really thanks

**Comment by antfu** [comment]
@marc-antoine-girard Looking forward to it, thank you!

**Comment by Gaiatux** [comment]
Hello, your app is really cool, I use it in my job (building architecture) to sketch over my plans to communicate with my collaborators. It only lacks the possibility of making straight lines with the SHIFT key.
Would it be possible to add this function? 
Thank you!

**Comment by Gaiatux** [comment]
> 
> 
> is there any way to create shortcuts? how to press ctrl + 1 to use the pen and ctrl + 2 to activate the eraser?
> 
> if there is no, would there be any way to implement it?
> 
> I really loved the program it is very good literally the best I have used so far being that I paid $$ 79 for a program with the same purpose and yours is much better, I just really would like to have shortcuts
> 
> thank you for your attention
> 
> iann ortnau

Hello iann,
In the last release we created shortcuts such as [B] Brush mode, [L] Line Mode and [E] or [D] Eraser mode.
SYS
