### ISSUE TITLE
Error while opening the app

### ISSUE THREAD

**Issue by Svk1190** [antfu/live-draw#13]
When I open the live-draw app, it gives an error message "To run this application, you must install .NET. Would you like to download it now?" And then it proceeds to the URL [https://dotnet.microsoft.com/download/dotnet/5.0/runtime/](https://dotnet.microsoft.com/download/dotnet/5.0/runtime/). Accordingly I install the .NET Desktop Runtime version 5.0.6. But even after the installation, the live-draw app refuses to launch, and continues to show the same error message.

**Comment by jhxxs** [comment]
Same thing happened to me.

**Comment by Wxh16144** [comment]
me too, I installed it, but I didn't restart the computer. I was wondering if I need to restart the computer

**Comment by 0lm** [comment]
Download and install Net 5.0 x86 version.

**Comment by ab28dev** [comment]
> Download and install Net 5.0 x86 version.

@jhxxs @Wxh16144 Did the above method solve your issue?

**Comment by 0lm** [comment]
> 
> 
> > Download and install Net 5.0 x86 version.
> 
> @jhxxs @Wxh16144 Did the above method solve your issue?

It did. Wehn you only have Net 5.0 x64 installed, it will give error. It looks like live-draw needs Net 5.0 x86 version instead.
I had the same issue. When I installed only x64 version of NET 5.0, it still gave me error. So, I installed x86, too, to check if it works then. And it worked.

**Comment by ab28dev** [comment]
It seems so.

**Comment by Nephty** [comment]
Had the same issue, downloading the x86 version worked.
