### ISSUE TITLE
linedraw 1.1 asks for newer .NET Core

### ISSUE THREAD

**Issue by kookma** [antfu/live-draw#14]
Use on Windows , linedraw-1.1.exe asks to download the newer .NET

Downloaded .NET 5 from below site
https://dotnet.microsoft.com/download/dotnet/5.0/runtime/?utm_source=getdotnetcore&utm_medium=referral

Still linedraw asks to install newers .NET and shows above message

**Comment by kookma** [comment]
![286_LiveDraw-0 1 1](https://user-images.githubusercontent.com/830394/119327907-bd2fa800-bc98-11eb-80fa-0bb2353dabd1.png)

The message is displayed by linedraw-1.1

**Comment by 0lm** [comment]
Download the x86 version of Net 5.0

**Comment by kookma** [comment]
Yes, Install >Net Core 5 x86 on Windows 64 worked for me!
