### ISSUE TITLE
Can't I just make the FitToCurve property apply while drawing the Ink?

### ISSUE THREAD

**Issue by SID9-HoneyBee** [antfu/live-draw#18]
If the FitToCurve property of the InkCanvas is True, the calibration will occur after every handwriting is finished. (About the outline)
Is it possible to apply the same effect as this property while drawing Ink?

**Comment by ab28dev** [comment]
@SID9-HoneyBee I didn't quite understand what you are refering to. Can you explain a bit more?

**Comment by SID9-HoneyBee** [comment]
thank you for the reply.
First I want to say that your project is very good.

My question may be a bit out of context for your project.
First of all, I'll say I'm sorry.

If the FitToCurve property is True,
After all drawing is finished (StylusUp), the drawn stroke is corrected to a smooth shape.

I would like to discuss with you how this can be continuously calibrated while it is being drawn (Stylus Move, Drawing).

**Comment by ab28dev** [comment]
This project is developed by @antfu. Later on people started contributing to it. 

No need to be sorry.

> I would like to discuss with you how this can be continuously calibrated while it is being drawn (Stylus Move, Drawing).
I really don't have any idea how this can be continously calibrated. I will need to study about this. I haven't done much in drawing / graphics.

You can discuss with others who have knowledge about this.

Can you please let me know if there is a possibility to improve this software in any way if we implement dynamic / continous calibration for drawing?

@antfu can you take part in discussing this? As I dont have much knowledge about it.
