### ISSUE TITLE
System compatibility

### ISSUE THREAD

**Issue by MostHated** [antfu/live-draw#20]
Hey there,
    I didn't see it specifically mentioned, is this Windows only, or would this be compatible with Linux as well?

Thanks,
-MH

**Comment by ab28dev** [comment]
This tool will work only on Windows OS.
If you can check the about section of the repo you can easily see that windows is mentioned.

**Comment by MostHated** [comment]
I probably would have easily seen it if it was in a proper place in the read me, and not the search meta keywords.
