### ISSUE TITLE
Erase by point doesn't show in the brush preview and changes size of pen.

### ISSUE THREAD

**Issue by ab28dev** [antfu/live-draw#24]
1. When using erase by point we can't see the size of the eraser.  It would be better it it could be shown in a new box near eraser.
2. If we change size of Erase by point the size of brush also changes which creates a mess.

**Comment by nle244** [comment]
What if the size of eraser changes dynamically along with the size of the line brush?

**Comment by ab28dev** [comment]
Eraser size changes along with the size of brush but it doesn't show anywhere. And we need to separate changing size of both. You can work on this.

**Comment by nle244** [comment]
Can I work on this issue?

**Comment by ab28dev** [comment]
Sure

**Comment by ab28dev** [comment]
@nle244 Your pull request had some conflicts. Kindly resolve it.
