### ISSUE TITLE
Installation Issue - LiveDraw 0.1.2 asks for .NET 5

### ISSUE THREAD

**Issue by caspercop** [antfu/live-draw#46]
I tied to install LiveDraw 0.1.2 in Windows 10 21H2.
As it asks for .NET 5, I installed it .NET 5.0 as it is linked by the installer as x64 and x86 for the respectiv installer version of LiveDraw.
Then I installed .Net 6.0.5 x64 and x86.
Whatever I installed, the LiveDraw installer didn't recognize the installed .NET versions and always asked for it again.

I'm not sure what I'm doing wrong, what else I could try.

Thank  you in advance!

**Comment by Kaiwawa** [comment]
Did you restart your PC?

**Comment by caspercop** [comment]
Thank you for your response!

Yes :) 
I did restart it several times now.

Here the .NET versions installed:
![image](https://user-images.githubusercontent.com/106406220/171567857-87bda533-da6e-4b2b-a1fe-2e6ce44e115a.png)

**Comment by Kaiwawa** [comment]
Man I aren't the Developer, sorry. I just have the same issue and I don't know how to fix. :(
But, did you tried to install the previous version? The 0.1.1?

**Comment by caspercop** [comment]
Same with V 0.1.1 :(

**Comment by ab28dev** [comment]
![image](https://user-images.githubusercontent.com/49103092/172013409-5747269b-d378-4e3f-82be-8c3778e00869.png)

I have microsoft .net runtime 5.0.12 installed on my system.
Live-draw works fine, image attached below. (you dont need to install live draw, just launch the exe)

![image](https://user-images.githubusercontent.com/49103092/172013544-383955ef-bcb9-402b-9d42-509ed29bc115.png)


Sol - Try the above version of .net run time. if it doesn't work then maybe install other apps related to .net and give a fresh installation to only the required apps.

**Comment by spaaacetoast** [comment]
Hi! I was running into the same issue. Running Windows 11. Had to remove any installed .net, windows runtime sdk thing. than i could install the .net runtime and was able to run it. seems its conflicting when newer or more than 1 version is installed

**Comment by rafma0** [comment]
I'm also on win11, tried installing net 5.0 runtime and it kept asking for the runtime after reboot. What I ended up doing is compiling it myself, setting the target as net core 3.1, installing netcore, and it's working now
