### ISSUE TITLE
building live-draw project error

### ISSUE THREAD

**Issue by dudenay** [antfu/live-draw#6]
@antfu 
I'm trying to solve compilation failure. After correcting the framework version to 4.8 in the LiveDraw.csproj I had to install msbuild 2016. Then I was able to compile until an error pointing to line 61 of CornerRadiusAnimation.cs:
public override Type TargetPropertyType => typeof(CornerRadius);

So when I launch build.bat in the Command prompt, it builds until it says:

CornerRadiusAnimation.cs(61,50): error CS1519: Invalid token '=>' in class, struct, or interface member declaration [C:\Users\xxxxx\xxxxx\live-draw-master\live-draw-master\LiveDraw\LiveDraw_i0ybxmcm_wpftmp.csproj]
CornerRadiusAnimation.cs(61,72): error CS1519: Invalid token ')' in class, struct, or interface member declaration [C:\
Users\xxxxx\xxxxx\live-draw-master\live-draw-master\LiveDraw\LiveDraw_i0ybxmcm_wpftmp.csproj]

And it returns a Build FAILED.

I don't understand what is going on. I would really like to be able to compile live-draw, the UI is beautifull. I really find it better than others on-screen annotation softwares.
Maybe the code needs a small update? Can you help me with this? I'm not a dev, but I try to solve this. Thanx!

**Comment by antfu** [comment]
Hi @dudenay, thanks for getting interested in this project! However, I am sorry as I no longer use Windows with a touchscreen, I may not be able to do any help on this at this moment. If anyone interested in making it work, feel free to maintain a fork - PRs for backporting your features are greatly welcome. As said, I am not able to maintain this project, I am happy to give permissions to collaborators who would like to help on it. Thanks a lot!

**Comment by rufanov** [comment]
By error text, it's seems like msbuild tries to compile project against very old .NET framework version(like 2.0, which doesn't have lambda expression support). Try to install [more modern .NET SDK](https://dotnet.microsoft.com/download/visual-studio-sdks) version.
