### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by kpitonak** [antfu/live-draw#7]
How do I install this app? Win 10. Running the .bat starts something but then there is no app running anywhere...

**Comment by antfu** [comment]
There are dist exes in the release page, did you try them?

**Comment by kpitonak** [comment]
...? Looks like it me... https://app.usebubbles.com/u8MfpMEEmixiynBA9BriER/no-exe-on-my-side-strange/ but no .exe file

**Comment by antfu** [comment]
https://github.com/antfu/live-draw/releases in the Assets

**Comment by kpitonak** [comment]
Thank you!
On 11/12/2020 3:05:24 PM, Anthony Fu <notifications@github.com> wrote:
https://github.com/antfu/live-draw/releases [https://github.com/antfu/live-draw/releases] in the Assets
