### ISSUE TITLE
Improve movement of ui

### ISSUE THREAD

**Issue by thALaZy** [antfu/live-draw#8]
when I try to move the ui it stops after about 10 ms here is a video but I have some c# code so it's way smoother:
public const int WM_NCLBUTTONDOWN = 0xA1;
        public const int HT_CAPTION = 0x2;
 
        [DllImport("user32.dll")]
        public static extern int SendMessage(IntPtr hWnd, int Msg, int wParam, int lParam);
 
        [DllImport("user32.dll")]
        public static extern bool ReleaseCapture();
 
        private void FormMoveable_MouseDown(object sender, System.Windows.Forms.MouseEventArgs e)
        {
            if (e.Button == MouseButtons.Left)
            {
                ReleaseCapture();
                SendMessage(Handle, WM_NCLBUTTONDOWN, HT_CAPTION, 0);
            }
        }

https://user-images.githubusercontent.com/54885958/104177670-d0408a80-5411-11eb-95e3-bbd912b6d3e9.mp4

**Comment by ab28dev** [comment]
This lag happens when we try to drag the window after clicking on "Release/Recover the control of drawing". Otherwise its smooth.

**Comment by ab28dev** [comment]
Solved
